<a href="https://colab.research.google.com/github/19PA1A0534/python-basics/blob/master/SVM_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SVM algorithm




* The full form of SVM is support vector machine.
* svm is mostly applicable for linearly separable data.
* It is a supervised learning algorithm which is used for both classification and regression.
* But at maximun cases it is used for classification technique.
*A hyperplane is a line that splits the input variable space.  
* The distance between the hyperplane and the closest data points is referred as margin.
*In SVM we convert the non linearly separable data into linearly separable by a method known as kernel method.
*There are different types of kernels.
*In kernel trick we convert 2D into 1D and 3D into 2D etc...








*In these we are applying the SVM algorithm for the iris dataset by taking the test size as 20% and random_state is 42.*

*And finally for the different kernels we are calculating the accuracy,precision and confusion matrix.*


In [0]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,roc_auc_score,mean_absolute_error,confusion_matrix,classification_report,precision_score,average_precision_score

In [109]:
#reading the given data
a=pd.read_csv('Iris.csv')
a

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [110]:
#printing the no.of rows and columns in the data
a.shape

(150, 6)

In [111]:
#printing the columns in the data
a.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [0]:
#taking the independent and dependent variables
x=a[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=a['Species']

In [0]:
#splitting the data into training and testing
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

*Here we are taking the linear kernel.



In [114]:
#preparing the model based on the training data
model=SVC(kernel='linear')
model.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [115]:
#predicting the test values
predicted=model.predict(x_test)
predicted

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [116]:
#printing the actual and predicted values
actual_predicted=pd.DataFrame({'actual':y_test,'predicted':predicted})
actual_predicted

actual        predicted
73   Iris-versicolor  Iris-versicolor
18       Iris-setosa      Iris-setosa
118   Iris-virginica   Iris-virginica
78   Iris-versicolor  Iris-versicolor
76   Iris-versicolor  Iris-versicolor
31       Iris-setosa      Iris-setosa
64   Iris-versicolor  Iris-versicolor
141   Iris-virginica   Iris-virginica
68   Iris-versicolor  Iris-versicolor
82   Iris-versicolor  Iris-versicolor
110   Iris-virginica   Iris-virginica
12       Iris-setosa      Iris-setosa
36       Iris-setosa      Iris-setosa
9        Iris-setosa      Iris-setosa
19       Iris-setosa      Iris-setosa
56   Iris-versicolor  Iris-versicolor
104   Iris-virginica   Iris-virginica
69   Iris-versicolor  Iris-versicolor
55   Iris-versicolor  Iris-versicolor
132   Iris-virginica   Iris-virginica
29       Iris-setosa      Iris-setosa
127   Iris-virginica   Iris-virginica
26       Iris-setosa      Iris-setosa
128   Iris-virginica   Iris-virginica
131   Iris-virginica   Iris-virginica
145   Iris-virginica   Iris-virginica
108   Iris-virginica   Iris-virginica
143   Iris-virginica   Iris-virginica
45       Iris-setosa      Iris-setosa
30       Iris-setosa      Iris-setosa

In [128]:
#printing the accuracy of the model
accuracy=accuracy_score(y_test,predicted)*100
accuracy

100.0

In [118]:
#printing the precision of the model
precision=precision_score(y_test,predicted,average=None)*100
precision

array([100., 100., 100.])

In [119]:
#printing the confusion matrix
confusion_matrix(y_test,predicted)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [120]:
#printing the classification report
classification_report(y_test,predicted)


'                 precision    recall  f1-score   support\n\n    Iris-setosa       1.00      1.00      1.00        10\nIris-versicolor       1.00      1.00      1.00         9\n Iris-virginica       1.00      1.00      1.00        11\n\n       accuracy                           1.00        30\n      macro avg       1.00      1.00      1.00        30\n   weighted avg       1.00      1.00      1.00        30\n'

*Here the kernel is rbf(radial basis function).



In [121]:
#preparing the model based on the training data
model=SVC(kernel='rbf')
model.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [122]:
#predicting the values
y_predicted=model.predict(x_test)
y_predicted

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [123]:
#printing the actual and predicted values
actual_predicted=pd.DataFrame({'actual':y_test,'predicted':y_predicted})
actual_predicted

actual        predicted
73   Iris-versicolor  Iris-versicolor
18       Iris-setosa      Iris-setosa
118   Iris-virginica   Iris-virginica
78   Iris-versicolor  Iris-versicolor
76   Iris-versicolor  Iris-versicolor
31       Iris-setosa      Iris-setosa
64   Iris-versicolor  Iris-versicolor
141   Iris-virginica   Iris-virginica
68   Iris-versicolor  Iris-versicolor
82   Iris-versicolor  Iris-versicolor
110   Iris-virginica   Iris-virginica
12       Iris-setosa      Iris-setosa
36       Iris-setosa      Iris-setosa
9        Iris-setosa      Iris-setosa
19       Iris-setosa      Iris-setosa
56   Iris-versicolor  Iris-versicolor
104   Iris-virginica   Iris-virginica
69   Iris-versicolor  Iris-versicolor
55   Iris-versicolor  Iris-versicolor
132   Iris-virginica   Iris-virginica
29       Iris-setosa      Iris-setosa
127   Iris-virginica   Iris-virginica
26       Iris-setosa      Iris-setosa
128   Iris-virginica   Iris-virginica
131   Iris-virginica   Iris-virginica
145   Iris-virginica   Iris-virginica
108   Iris-virginica   Iris-virginica
143   Iris-virginica   Iris-virginica
45       Iris-setosa      Iris-setosa
30       Iris-setosa      Iris-setosa

In [124]:
#printing the accuracy of the model
accuracy=accuracy_score(y_test,y_predicted)*100
accuracy

100.0

In [125]:
#printing the precision of the model
precision=precision_score(y_test,y_predicted,average=None)*100
precision

array([100., 100., 100.])

In [126]:
#printing the confusion matrix 
confusion_matrix(y_test,predicted)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [127]:
#printing the classification report
classification_report(y_test,predicted)

'                 precision    recall  f1-score   support\n\n    Iris-setosa       1.00      1.00      1.00        10\nIris-versicolor       1.00      1.00      1.00         9\n Iris-virginica       1.00      1.00      1.00        11\n\n       accuracy                           1.00        30\n      macro avg       1.00      1.00      1.00        30\n   weighted avg       1.00      1.00      1.00        30\n'

#conclusion:
**Therefore from the above by taking the different kernels we are getting the same accuracy,precision and confusion matrix.**

**Here we are getting the accuracy score is 100 which is a rare case.**

Done By:

CH.Bala Mahesh(19PA1A0534)